/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      width: {
        'calc-100-plus-84': 'calc(100% + 84px)',
        'calc-100-plus-37': 'calc(100% + 37px)',
      },
      maxWidth: {
        'calc-100-plus-84': 'calc(100% + 84px)',
      },
      gridTemplateColumns: {
        '3-min': 'repeat(3, min-content)',
      },
      fontFamily: {
        helvetica: ["var(--font-helveticaNeue)"],
        machina: ["var(--font-neueMachina)"],
        inter: ["var(--font-inter)"]
      },
      colors: {
        primary: "#06D6F8",
        primaryOrange: "#FF490F",
        mint: "#53D3AA",
      },
      backgroundImage: {
        homeBg: "url(../public/images/homeBg.webp)",
        homeBg2xl: "url(../public/images/homeBg2xl.webp)",
        homeBgmd: "url(../public/images/homeBgmd.webp)",
        homeBgsm: "url(../public/images/homeBgsm.webp)",
        searchBg: "url(../public/images/searchBg.webp)",
        searchBg2xl: "url(../public/images/searchBg2xl.webp)",
        searchBgmd: "url(../public/images/searchBgmd.webp)",
        searchBgsm: "url(../public/images/searchBgsm.webp)",
        scanBg: "url(../public/images/scanBg.webp)",
        scanBg2xl: "url(../public/images/scanBg2xl.webp)",
        scanBgmd: "url(../public/images/scanBgmd.webp)",
        scanBgsm: "url(../public/images/scanBgsm.webp)",
        salesBg: "url(../public/images/salesBg.webp)",
        salesBg2xl: "url(../public/images/salesBg2xl.webp)",
        salesBgmd: "url(../public/images/salesBgmd.webp)",
        salesBgsm: "url(../public/images/salesBgsm.webp)",
        auditorBg3xl: "url(../public/images/auditorBg3xl.webp)",
        auditorBg2xl: "url(../public/images/auditorBg2xl.webp)",
        auditorBgmd: "url(../public/images/auditorBgmd.webp)",
        // auditorBgsm: "url(../public/images/auditorBgsm.webp)",
        auditorBg: "url(../public/images/auditorBg.webp)",
        consultingBg: "url(../public/images/consultingBg.webp)",
        consultingBg2xl: "url(../public/images/consultingBg2xl.webp)",
        consultingBgmd: "url(../public/images/consultingBgmd.webp)",
        consultingBgsm: "url(../public/images/consultingBgsm.webp)",
        forAuditorsBg: "url(../public/images/auditorsBg.webp)",
        forAuditorsBg2xl: "url(../public/images/auditorsBg2xl.webp)",
        forAuditorsBgmd: "url(../public/images/auditorsBgmd.webp)",
        forAuditorsBgsm: "url(../public/images/auditorsBgsm.webp)",
        supplierBg: "url(../public/images/supplierBg.webp)",
        supplierBg2xl: "url(../public/images/supplierBg2xl.webp)",
        supplierBgmd: "url(../public/images/supplierBgmd.webp)",
        supplierBgsm: "url(../public/images/supplierBgsm.webp)",
        worldBg: "url(../public/images/earth.webp)",
        worldBg2xl: "url(../public/images/earth2xl.webp)",
        worldBgmd: "url(../public/images/earthmd.webp)",
        worldBgsm: "url(../public/images/earthsm.webp)",
        blackGray: "linear-gradient(to right, black 75%, #414141 25%)",
        blueGray: "linear-gradient(to left, #F6F6F6 77%, #06D7F9 23%)",
        blueGrayFromTopcustomxs:
          "linear-gradient(to top, #F6F6F6 65%, #06D7F9 35%)",

        blueGrayFromTop: "linear-gradient(to top, #F6F6F6 75%, #06D7F9 25%)",
        discoverConnectExcel2xl: "url(../public/images/discover-connect-excel2xl.webp)",
        discoverConnectExcelmd: "url(../public/images/discover-connect-excelmd.webp)",
        discoverConnectExcel: "url(../public/images/discover-connect-excel.webp)",
        bgFooter2xl: "url(../public/images/bg-footer2xl.png)",
        bgFootermd: "url(../public/images/bg-footermd.png)",
        bgFooter: "url(../public/images/bg-footer.png)",
        solution2Bg3xl: "url(../public/images/solution2Bg3xl.png)",
        solution2Bg2xl: "url(../public/images/solution2Bg2xl.webp)",
        solution2Bgmd: "url(../public/images/solution2Bgmd.png)",
        solution2Bg: "url(../public/images/solution2Bg.png)",

        solutionBg3xl: "url(../public/images/solutionBg3xl.webp)",
        solutionBgmd: "url(../public/images/solutionBgmd.webp)",
        solutionBg: "url(../public/images/solutionBg.webp)",
        // discoverConnectExcelsm: "url(../public/images/discover-connectexcel.webp)",
      },
      screens: {
        xs: "361px",
        customxs: "440px",
        sm: "640px",
        customsm: "700px",
        md: "768px",
        md2: "900px",
        lg: "1024px",
        lg2: "1140px",
        xl: "1280px",
        "2xl": "1440px",
        "3xl": "1920px" 
        // => @media (min-width: 1440px) { ... }
      },
    },
  },
  plugins: [],
};
